  name: Legendary Items
  main: com.gmail.raldor46.LegendaryItems.LegendaryItems
  version: 0.1
  commands:
    LegendarySword:
      description: This is a demo command.
      usage: /<command> [action]
      permission: LegendaryItems.items
      permission-message: You don't have <permission>